parent: $LVSR/exp/billion_words/configs/actor_critic4.yaml
net:
    criterion:
        solve_bellman: True
training:
    external_policy: False
    external_targets: True
stages:
    critic_pretraining:
        training:
            num_batches: 30000
